### ISSUE TITLE
JMH Scala CountSetTest is incorrectly using the CountSet in the java impl.

### ISSUE THREAD

**Issue by ncornwell** [goldmansachs/gs-collections#15]
It looks like the JMH Scala CountSetTest is incorrectly using the CountSet in the java impl.

I also removed my pull request as it looks like you guys prefer to commit internally.

**Comment by goldmansachs** [comment]
Thank you for reporting this. Fixed in https://github.com/goldmansachs/gs-collections/commit/1a86f46
