### ISSUE TITLE
relax visibility of arraylist items / ability to addAll efficiently

### ISSUE THREAD

**Issue by phraktle** [goldmansachs/gs-collections#19]
If one wants to append a IntArrayList to another IntArrayList, there's an extra copy involved due to the call to toArray():
```
   public boolean addAll(IntIterable source)
    {
        return this.addAll(source.toArray());
    }
```

Also, please relax the visibility of items to protected, so one can subclass this collection. As I understand, that was the design rationale for FastList vs. JDK ArrayList, but looks like the same mistake is repeated here :)

**Comment by goldmansachs** [comment]
Thanks for reporting this. We'll pick this up in the next minor release.
