### ISSUE TITLE
Binary search for primitive lists

### ISSUE THREAD

**Issue by phraktle** [goldmansachs/gs-collections#20]
Provide the equivalent of ListIterable#binarySearch on primitive lists.

**Comment by aewhite** [comment]
WIthout a better way of showing my support for this request: :+1:

**Comment by wguedes01** [comment]
Should this issue be closed? http://www.goldmansachs.com/gs-collections/javadoc/5.0.0/com/gs/collections/api/list/ListIterable.html#binarySearch(T)

**Comment by goldmansachs** [comment]
This issue will be fixed in the upcoming 7.0 release.
