### ISSUE TITLE
Avoid double probe

### ISSUE THREAD

**Issue by chrisc36** [goldmansachs/gs-collections#34]
Another performance issue, I can look into patching this on the  Eclipse Collections project as well.

For, primitive object maps, "<primitive>ObjectHashMap" the "getIfAbsent" method calls the `probe` function twice, basically doubling the cost of a hash lookup. The problem are the lines:

``` java
        int index = this.probe(key);
        if (this.keys[this.probe(key)] == key)
```

the precomputed `index` value is recomputed from scratch on the second line!

**Comment by itohro** [comment]
Very good catch and please do submit a pull request to Eclipse Collections!

**Comment by nikhilnanivadekar** [comment]
@chrisc36 this has been fixed in [Eclipse Collections](https://github.com/eclipse/eclipse-collections) via PR: https://github.com/eclipse/eclipse-collections/pull/401
It will be a part of Eclipse Collections 9.1.0 release.
